#!/bin/ash

. /init_functions
. /config

run_hookfunctions() {
    local hook fn=$1 desc=$2

    shift 2
    for hook in "$@"; do
        [ -x "/hooks/$hook" ] || continue

        unset -f "$fn" # needs -f to unset functions
        . "/hooks/$hook"
        type "$fn" >/dev/null || continue

        msg ":: running $desc [$hook]"
        "$fn"
    done
}

SHUTDOWN_HOOKS=$(echo $EARLYHOOKS $HOOKS $LATEHOOKS $CLEANUPHOOKS | sed -e 's: \+:\n:g' | sort | uniq)
export SHUTDOWN_HOOKS

if grep -e 'break=\(y\|\(pre\)\?shutdown\)' /proc/cmdline > /dev/null; then
    echo ":: Pre-shutdown break requested, type 'exit' to resume operation"
    launch_interactive_shell
fi

run_hookfunctions 'run_shutdown' 'shutdown hook' ${SHUTDOWN_HOOKS}

if grep -e 'break=\(y\|\(post\)\?shutdown\)' /proc/cmdline > /dev/null; then
    echo ":: Shutdown break requested, type 'exit' to resume operation"
    launch_interactive_shell
fi

exec /shutdown.orig $@
