#!/bin/sh
#
# This hook mounts a file system that is overlayed over the root file system
# already mounted at ~/new_root~. This is useful for live CDs, testing, and
# any where else temporary changes and/or unmodifiable root file systems
# are needed.
#
# Input boot arguments:
#
#           overlay_upper  The block device containing the overlay file system.
#                          ~none~ creates a tmpfs.
#      overlay_upper_type  The file system type of the overlay file system.
#   overlay_upper_options  Any mount options for the overlay.
#
# File systems are mounted to:
#
#   /run/overlay/ro  The source file system.
#   /run/overlay/rw  The overlay file system.
#         /new_root  The complete file system
#
# Upon system shutdown the file systems are unmounted in the reverse order.
#

OVERLAY_MNT_ROOT="/run/overlay"

is_overlay_root() {
	if [[ "${overlay_upper}" == "" ]]; then
		return 1
	else
		return 0
	fi
}

run_latehook() {
	is_overlay_root || return 0

	msg "Preparing overlay file system"

	mkdir -p ${OVERLAY_MNT_ROOT}/rw ${OVERLAY_MNT_ROOT}/ro

	#mount -oremount,rw /new_root
	mount -omove /new_root ${OVERLAY_MNT_ROOT}/ro

	if [[ "${overlay_upper}" != 'none' ]]; then
		msg "Checking overlay ${overlay_upper}"
		[ ! -e "${overlay_upper}" ] && overlay_upper="$(resolve_device "${overlay_upper}")"
		if [[ "${overlay_upper_fsck}" != '0' ]] && [ -b "${overlay_upper}" ] && ! fsck_device "${overlay_upper}"; then
			err "Failed to fsck overlay root: ${overlay_upper}"
		fi
	fi

	msg "Mounting overlay ${overlay_upper}"
	if ! mount -t "${overlay_upper_type:-auto}" -o "${overlay_upper_options:-rw}" "${overlay_upper}" ${OVERLAY_MNT_ROOT}/rw ; then
                run_hookfunctions 'run_emergencyhook' 'emergency hook' $EMERGENCYHOOKS
		err "Failed to mount overlay root ${overlay_upper} at ${OVERLAY_MNT_ROOT}/rw"
		launch_interactive_shell
	fi

	[ ! -d ${OVERLAY_MNT_ROOT}/rw/data ] && mkdir ${OVERLAY_MNT_ROOT}/rw/data
	[ ! -d ${OVERLAY_MNT_ROOT}/rw/work ] && mkdir ${OVERLAY_MNT_ROOT}/rw/work

	OVERLAY_OPTS="index=off,lowerdir=${OVERLAY_MNT_ROOT}/ro,upperdir=${OVERLAY_MNT_ROOT}/rw/data,workdir=${OVERLAY_MNT_ROOT}/rw/work"
	[[ "${overlay_options}" != "" ]] && OVERLAY_OPTS="${overlay_options},${OVERLAY_OPTS}"
	if ! mount -t overlay none /new_root -o "${OVERLAY_OPTS}" ; then
                run_hookfunctions 'run_emergencyhook' 'emergency hook' $EMERGENCYHOOKS
		err "Overlay failed to mount: mount -t overlay none /new_root -o \"${OVERLAY_OPTS}\""
		launch_interactive_shell
	fi
}

umount_tree()
{
  local DIR="$1"
  for d in $(grep "${DIR}" /proc/mounts | cut -d ' ' -f 2 | sort -r); do
    msg "Unmounting ${d}"
    umount "${d}" || msg failed
  done
}

run_shutdown()
{
	if grep -e '/run/overlay/r.' /proc/mounts > /dev/null; then
		msg "Unmounting overlay file systems..."
		[ -d /run/livecd ] || mkdir /run/livecd
		if ps | grep plymouth > /dev/null; then
			plymouth quit
		fi
		umount_tree /oldroot
		umount_tree /run/overlay/
	fi
}
